// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M144.yaml
#pragma once

#define PIN_0 D4
#define PIN_1 D3
#define PIN_2 C9
#define PIN_4 C8
#define PIN_5 C7
#define PIN_6 G8
#define PIN_7 D7
#define PIN_8 G9
#define PIN_9 G10
#define PIN_10 G11
#define PIN_11 G12
#define PIN_12 G13
#define PIN_13 E11
#define PIN_14 E12
#define PIN_17 D14
#define PIN_15 E8
#define PIN_16 E7
#define PIN_18 E9
#define PIN_19 G14
#define PIN_20 B4
#define PIN_21 B5
#define PIN_22 B6
#define PIN_23 B7
#define PIN_24 B8
#define PIN_54 EFI_ADC_14
#define PIN_55 EFI_ADC_15
#define PIN_56 EFI_ADC_8
#define PIN_57 EFI_ADC_9
#define PIN_58 EFI_ADC_10
#define PIN_59 EFI_ADC_11
#define PIN_60 EFI_ADC_12
#define PIN_61 EFI_ADC_13
#define PIN_62 EFI_ADC_0
#define PIN_63 EFI_ADC_1
#define PIN_64 EFI_ADC_2
#define PIN_65 EFI_ADC_3
#define PIN_66 EFI_ADC_4
#define PIN_67 EFI_ADC_5
#define PIN_68 EFI_ADC_6
#define PIN_69 EFI_ADC_7
