// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M144.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::D7, // INJ1
	Gpio::G9, // INJ2
	Gpio::G10, // INJ3
	Gpio::G11, // INJ4
	Gpio::G12, // INJ5
	Gpio::G13, // INJ6
	Gpio::D4, // IGN1
	Gpio::D3, // IGN2
	Gpio::C9, // IGN3
	Gpio::C8, // IGN4
	Gpio::C7, // IGN5
	Gpio::G8, // IGN6
	Gpio::E11, // ISO Digital IN3
	Gpio::E12, // ISO Digital IN1
	Gpio::D14, // ISO Digital IN2
	Gpio::E8, // VR1
	Gpio::E7, // VR2
// "INJ1",
// "INJ2",
// "INJ3",
// "INJ4",
// "INJ5",
// "INJ6",
// "IGN1",
// "IGN2",
// "IGN3",
// "IGN4",
// "IGN5",
// "IGN6",
// "ISO Digital IN3",
// "ISO Digital IN1",
// "ISO Digital IN2",
// "VR1",
// "VR2",
}
