// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/M144.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::C7:
			return "IGN5";
		case Gpio::C8:
			return "IGN4";
		case Gpio::C9:
			return "IGN3";
		case Gpio::D14:
			return "ISO Digital IN2";
		case Gpio::D3:
			return "IGN2";
		case Gpio::D4:
			return "IGN1";
		case Gpio::D7:
			return "INJ1";
		case Gpio::E11:
			return "ISO Digital IN3";
		case Gpio::E12:
			return "ISO Digital IN1";
		case Gpio::E7:
			return "HALL2-VR2";
		case Gpio::E8:
			return "HALL1-VR1";
		case Gpio::E9:
			return "HALL3-VR3";
		case Gpio::G10:
			return "INJ3";
		case Gpio::G11:
			return "INJ4";
		case Gpio::G12:
			return "INJ5";
		case Gpio::G13:
			return "INJ6";
		case Gpio::G8:
			return "IGN6";
		case Gpio::G9:
			return "INJ2";
		default:
			return nullptr;
	}
	return nullptr;
}
